name: hearing_journey
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  provider: ^6.0.5
  path_provider: ^2.0.5
  shared_preferences: ^2.0.10
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.0
  csv: ^5.1.1
  accordion: ^2.6.0
  firebase_auth: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/fragebogen.jpg
     - assets/tipps.jpg
     - assets/questions.csv
     - assets/tips.csv

