// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARcCKQjBf0yDt5XkCRmJNlUA-Q76eCO7s',
    appId: '1:1097092791568:web:d63ebc6fa1414890c6f995',
    messagingSenderId: '1097092791568',
    projectId: 'afe-hearing-journey',
    authDomain: 'afe-hearing-journey.firebaseapp.com',
    storageBucket: 'afe-hearing-journey.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVB3j17xPAYLSOU11ZI1qTg7IWr6n18jo',
    appId: '1:1097092791568:android:1d28867a75dfbdf1c6f995',
    messagingSenderId: '1097092791568',
    projectId: 'afe-hearing-journey',
    storageBucket: 'afe-hearing-journey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8qk-JLVx7EQAtWQ_0DfSK6-qZIoeFOkI',
    appId: '1:1097092791568:ios:3257bcb9ced85cdcc6f995',
    messagingSenderId: '1097092791568',
    projectId: 'afe-hearing-journey',
    storageBucket: 'afe-hearing-journey.appspot.com',
    iosBundleId: 'com.example.hearingJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8qk-JLVx7EQAtWQ_0DfSK6-qZIoeFOkI',
    appId: '1:1097092791568:ios:6743a3bfab62537bc6f995',
    messagingSenderId: '1097092791568',
    projectId: 'afe-hearing-journey',
    storageBucket: 'afe-hearing-journey.appspot.com',
    iosBundleId: 'com.example.hearingJourney.RunnerTests',
  );
}
